# Generated by Django 5.0.7 on 2024-08-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_post_post_date_alter_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
