# Generated by Django 5.0.7 on 2024-08-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Hello World', max_length=255),
            preserve_default=False,
        ),
    ]
